### ISSUE TITLE
+/- in wiring

### ISSUE THREAD

**Issue by der--flo** [patrickcollins12/esphome-fan-controller#1]
Hi, awesome little project !

But for me it looks like your schematic has a little error with plus and minus switched on the stepdown side and the bridge to ground on 3.3...
![2022-05-10_16-09](https://user-images.githubusercontent.com/1823727/167649032-a001bc36-9f36-4751-86cc-e4bcc7723100.png)
s

**Comment by patrickcollins12** [comment]
Thanks! I'll correct it.

**Comment by patrickcollins12** [comment]
Done, thanks.
