### ISSUE TITLE
Reading multiple tacho signals separate

### ISSUE THREAD

**Issue by CzarofAK** [patrickcollins12/esphome-fan-controller#15]
Have you ever tried to read multiple tacho signals to check individual fans RPMs?

**Comment by DunklesKaltesNichts** [comment]
Here is an example with 2 fans.
https://github.com/patrickcollins12/esphome-fan-controller/issues/10#issuecomment-1403371213

**Comment by patrickcollins12** [comment]
You're right @CzarofAK. Two fans need two separate pins for the tacho. I have not personally implemented the tacho so I didn't notice this error in the diagram.
