### ISSUE TITLE
Fan Connector Type Doesn't Seem Right

### ISSUE THREAD

**Issue by gcortes** [patrickcollins12/esphome-fan-controller#3]
I wanted to do this project to cool my electronics closet. I'm not an EE and haven't done electronics in ages so I could be wrong about this.

I bought the same Corsair fans as you specified (LM 120). In you image, you specify a JST connector. My research shows that the connector on the fan connects to a Molex 0470531000. It has a 2.54mm pitch as opposed to the 2.5mm of the JST connectors. There appear to be 4 different types, all 2.5mm. I'm going to go with the Molex as I'm going to build it on a solder breadboard.

The other confusing item is the pin out for the fan. Your wiring diagram shows using the first three pins. The third pin is Tach. In you description, you mention not using this. The web documentation I've found says pin 4 is control/PWM. I'm assuming that's the one you meant.

Thanks for posting this project. I've been thinking about how I could do something similar for quite some time. Now I have a solution.

**Comment by patrickcollins12** [comment]
Sorry for the delay. I must have got lucky and got 2.54mm jst. There is no standards for jst but if you buy it from an arduino shop they normally fit the 2.54mm (.1”) standard perfboard pin spacing.

I can’t recall which pin is tach but I left it unwired. The fan accepts 3.3v or 5v as PWM data no problem.
