### ISSUE TITLE
3 wire fan

### ISSUE THREAD

**Issue by alfadex** [patrickcollins12/esphome-fan-controller#30]
Hi, is it going to operate with 3 wire fan? I have two of these and would lik to try. I assume the fourth pin that is missing is tachometer pin,so i will miss the feedback

**Comment by patrickcollins12** [comment]
Not really. 3-pin fans are normally +/- and tachometer. You need pwm to have variable voltage (for different speeds). 

To use those 3-pin fans, you could use a logic level mosfet to create an external pwm controller.

**Comment by alfadex** [comment]
i see,so at 4 pin fan the mosfet is inside the fan. i have to use a moset out of the fan to control with pwm 24 volt fan. In code  you use tachometer pin only for detecting if fan is blocked?

My thought is, let suppose for every cycle of fan we get 1 Hz from tachometer. We test our fan at max voltage and we get  10000 rpm. 
If for example we have 30 Celcius, and we need fan to operate at 30%, pwm pin of esp8266 can lower it's output and when our fan reach 3000 rpm and get 3KHz at tachometer pin ,get pwm out stabilized and rpm stay at 3000 rpm. I mean watch tach pin ,and automaticly microcontroller adjust pwm pin  (increase or decrease) output until reach the condition

**Comment by patrickcollins12** [comment]
On your first point, that is correct, in a 4-pin, the mosfet is inside the fan. If you want to tinker, learn and solder, buy the mosfet. If not, buy a new 4-pin pwm fan.

In regards to the second paragraph: no you're over thinking it. In fact my project doesn't even use the tach pin. If I did use tach, it would be to detect if the fan was blocked. In this project the main input is voltage 0-12v. Then the output is watching the temperature change. This is done using a pid controller. Tachometer is not needed.
