### ISSUE TITLE
Can I do this project with a fan control with potentiometer?

### ISSUE THREAD

**Issue by decorsodario** [patrickcollins12/esphome-fan-controller#31]
Hi, I bought a ventilation kit with potentiometer from Aliexpress,
![immagine](https://github.com/patrickcollins12/esphome-fan-controller/assets/140659188/98c1977f-3353-4e74-8313-820011399e80)
![Immagine WhatsApp 2024-04-24 ore 20 25 38_76bd5cda](https://github.com/patrickcollins12/esphome-fan-controller/assets/140659188/d4966732-e77d-4896-8663-ace6ecf72540)

 now I can integrate it into the home assistant with a smart socket, is it possible to connect this potentiometer to esp32?
![Immagine WhatsApp 2024-04-24 ore 20 26 48_95c8bdb7](https://github.com/patrickcollins12/esphome-fan-controller/assets/140659188/f88e36c0-39f7-4973-9446-0c2f8cc82e14)
thank you for your availability and kindness

**Comment by patrickcollins12** [comment]
No.

This potentiometer kit has a power supply and analog potentiometer built in. 

I would only keep the fans, cut the head of the female socket and rewire it to use esp32 digitally. 

Then you would also need a new power supply.
