### ISSUE TITLE
2 powers Input (5v & 12v) [ QUESTION ]

### ISSUE THREAD

**Issue by PaulBiod** [patrickcollins12/esphome-fan-controller#33]
Hi, thanks for your project, I will try to build it with a noctua fan for my fish tank.
BTW, I have a question : I am planning to use 12v power adapter for the fan and micro usb  cable for the esp32. In this particulary case, should the ground line of the 12v power be also connected to the ground line of the esp32 ?
Thanks

**Comment by DunklesKaltesNichts** [comment]
yes

**Comment by PaulBiod** [comment]
Thanks for your confirmation

**Comment by patrickcollins12** [comment]
I've updated the documentation to make this more clear
