### ISSUE TITLE
Must add platform: esphome under ota in yaml

### ISSUE THREAD

**Issue by jrichey25** [patrickcollins12/esphome-fan-controller#36]
I was getting this error: "At least one platform must be specified for 'ota'; add 'platform: esphome' for original OTA functionality" until I added the esphome platform under ota in the yaml, referencing this thread: https://github.com/esphome/esphome/pull/6459

I apologize if this isn't the right place to suggest adding documentation, I just thought it might be helpful and saves some noobies like myself some time.

**Comment by patrickcollins12** [comment]
Appreciate it. Resolved.
