### ISSUE TITLE
error: operation on 'write_val' may be undefined [-Werror=sequence-point]

### ISSUE THREAD

**Issue by tuplink** [patrickcollins12/esphome-fan-controller#38]
in proxy_output template the lamda block appears to be incorrect

write_val = state*1.0;  <----- this is the line with the issue, i beleive "write_val = " needs removed.

    (CONDITION) ? then this : else XXXXX   cant set an undeclared variable till it exists
    
making this change allows compile

**Comment by patrickcollins12** [comment]
Thanks... dumb error... I'm surprised it used to compile
