### ISSUE TITLE
Offline capability

### ISSUE THREAD

**Issue by claib** [patrickcollins12/esphome-fan-controller#6]
Hi Patrick
cool project !
Is there a way to make the setup offline resilient ?
- insure the fan regulates the temperature, even if there is no wifi connection, or homeassistant not available 

mercimille
Christoph

**Comment by DunklesKaltesNichts** [comment]
it wshould works offline if:
- Turn of the HA Api or set reboot_timeout to zero.
- disable wifi or set reboot_timeout to zero

**Comment by patrickcollins12** [comment]
Yes ESPHome will work without internet and the PID controller will continue to function. Of course you won't get reporting back to Home Assistant during that period.
